自由帳画面の作成
Project-Null-Undefined/music-scribble pull request #11
Opened 2024-09-11 09:36 UTC by karasuneo

2024-09-11 12:56 UTC, SatooRu65536 requested changes

2024-09-11 12:56 UTC, SatooRu65536 commented on src/app/draw/features/FreeDrawing/components/DrawingText/styles.module.scss
> +@use "@/styles/variables.scss" as *;
next.config.mjs で全てのscssファイルに追加されるようになってるので不要です！
```
  sassOptions: {
    additionalData: `
      @use '@/styles/colors.scss' as *;
      @use '@/styles/variables.scss' as *;    
      @use '@/styles/mixins.scss' as *;
    `,
  },
```

2024-09-12 07:38 UTC, karasuneo commented on src/app/draw/features/FreeDrawing/components/DrawingText/styles.module.scss
> +@use "@/styles/variables.scss" as *;
直しました！

2024-09-12 13:17 UTC, SatooRu65536 approved these changes

2024-09-12 13:25 UTC, merged