Issues/#3
Project-Null-Undefined/music-scribble pull request #14
Opened 2024-09-11 15:59 UTC by NenfuAT

UI部分はできたと思うので確認お願いします

実装内容
 - 時間経過で左から右に進むゲージの作成
   - スペースキーを押したらスタート
 - スペースキーを押していた区間のハイライト
 - スペースキーを押させるためのガイドテキスト

2024-09-11 16:22 UTC, SatooRu65536 requested changes

2024-09-11 16:22 UTC, SatooRu65536 commented on src/app/tap/features/RecordRhythm/components/RhythmBar/index.tsx
> +  };
コンポーネント内でコンポーネントを定義するのはあまり良くないので外に出してあげたほうがいいと思います！

ProgressBarがレンダリングされるたびにrenderHighlightedSectionsもレンダリングされてしまうためです
（memo化すれば回避できますが、ちゃんとコンポーネント分けすればmemoは不要と公式のどっかに書かれてます）

2024-09-11 16:22 UTC, SatooRu65536 commented on src/app/tap/features/RecordRhythm/components/RhythmBar/index.tsx
> +            position: 'relative',
ここら辺の変数に依存していないCSSは `src/app/tap/features/RecordRhythm/components/RhythmBar/style.module.scss` で書いたほうがいいです！
（他にもあるかも）

2024-09-11 16:22 UTC, SatooRu65536 commented on src/app/tap/features/RecordRhythm/components/RhythmBar/index.tsx
> +                backgroundColor: colors.primaryColor, // ハイライト色の適用
基本的には `@/styles/*.module.scss` は使わず、scssファイル内で↓のようにscss変数を使ったほうがいいです
```scss
background-color: $primary-color;
```

@/styles/*.module.scss はTSからCSSの値を動的に変更する場合用だと思ってもらえればOKです
ユーザに色を選んでもらいたいときとか

2024-09-11 16:22 UTC, SatooRu65536 commented on src/app/tap/features/RecordRhythm/components/RhythmBar/style.module.scss
> +	background-color: #eee;
統一するために色は直接指定せずにSCSS変数を使って欲しいです！
```suggestion
	background-color: $background-color
```

数字と色は全てSCSS変数を使うことが**理想**(結構面倒なので普段はやらない)です
`border-radius` 等の`src/styles/*.module.scss` で定義されているものは他のも置き換えて欲しいです

2024-09-12 02:37 UTC, NenfuAT commented on src/app/tap/features/RecordRhythm/components/RhythmBar/style.module.scss
> +	background-color: #eee;
ゲージが溜まってない時の灰色の部分なんだけど`src/styles/*.module.scss`の方にない色なんだけど勝手に増やしていいってこと?

2024-09-12 06:36 UTC, NenfuAT commented on src/app/tap/features/RecordRhythm/components/RhythmBar/index.tsx
> +  };
Doneのはず

2024-09-12 06:36 UTC, NenfuAT commented on src/app/tap/features/RecordRhythm/components/RhythmBar/index.tsx
> +            position: 'relative',
Done

2024-09-12 06:36 UTC, NenfuAT commented on src/app/tap/features/RecordRhythm/components/RhythmBar/index.tsx
> +                backgroundColor: colors.primaryColor, // ハイライト色の適用
Done

2024-09-12 06:36 UTC, NenfuAT commented on src/app/tap/features/RecordRhythm/components/RhythmBar/style.module.scss
> +	background-color: #eee;
Done

2024-09-12 06:38 UTC, NenfuAT commented
修正できたと思うので再確認お願いします

2024-09-12 06:43 UTC, NenfuAT commented
修正できたと思うので再確認お願いします

2024-09-12 13:25 UTC, SatooRu65536 approved these changes
よさそうです！

2024-09-12 13:56 UTC, NenfuAT commented
マージしちゃいます!

2024-09-12 13:56 UTC, merged